# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import products_pb2 as products__pb2


class ProductInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductInfo = channel.unary_unary(
                '/ProductInfo/GetProductInfo',
                request_serializer=products__pb2.ProductID.SerializeToString,
                response_deserializer=products__pb2.Product.FromString,
                )
        self.GetAllProductsInfo = channel.unary_unary(
                '/ProductInfo/GetAllProductsInfo',
                request_serializer=products__pb2.Success.SerializeToString,
                response_deserializer=products__pb2.Products.FromString,
                )
        self.AddProduct = channel.unary_unary(
                '/ProductInfo/AddProduct',
                request_serializer=products__pb2.Product.SerializeToString,
                response_deserializer=products__pb2.Success.FromString,
                )


class ProductInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllProductsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=products__pb2.ProductID.FromString,
                    response_serializer=products__pb2.Product.SerializeToString,
            ),
            'GetAllProductsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProductsInfo,
                    request_deserializer=products__pb2.Success.FromString,
                    response_serializer=products__pb2.Products.SerializeToString,
            ),
            'AddProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProduct,
                    request_deserializer=products__pb2.Product.FromString,
                    response_serializer=products__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProductInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProductInfo/GetProductInfo',
            products__pb2.ProductID.SerializeToString,
            products__pb2.Product.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllProductsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProductInfo/GetAllProductsInfo',
            products__pb2.Success.SerializeToString,
            products__pb2.Products.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProductInfo/AddProduct',
            products__pb2.Product.SerializeToString,
            products__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
